"""Update foreign key ondelete behaviors

Revision ID: 9d2763fc8605
Revises: d8bac87297c0
Create Date: 2026-03-24 15:45:52.623934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2763fc8605'
down_revision: Union[str, Sequence[str], None] = 'd8bac87297c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('success_notes_category_id_fkey'), 'success_notes', type_='foreignkey')
    op.drop_constraint(op.f('success_notes_owner_id_fkey'), 'success_notes', type_='foreignkey')
    op.create_foreign_key(None, 'success_notes', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'success_notes', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'success_notes', type_='foreignkey')
    op.drop_constraint(None, 'success_notes', type_='foreignkey')
    op.create_foreign_key(op.f('success_notes_owner_id_fkey'), 'success_notes', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('success_notes_category_id_fkey'), 'success_notes', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
